name: Release

on:
  push:
    tags:
      - '*.*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build project
        run: |
          mkdir dt-metrics-gap-list
          cp -r dt-metrics-gap-list.php charts languages spinner.svg version-control.json LICENSE SECURITY.md dt-metrics-gap-list/
          zip -r dt-metrics-gap-list.zip dt-metrics-gap-list
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"
          tag_name: ${{ github.ref }}
          name: Release ${{ github.ref }})
          draft: false
          prerelease: false
          files: ./dt-metrics-gap-list.zip
          generate_release_notes: true
